[build]
  publish = "."
  command = "echo 'No build required - static site'"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/user"
  to = "/user/index.html"
  status = 200

[[redirects]]
  from = "/user/*"
  to = "/user/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/user/index.html"
  status = 200
